FROM node:22-bookworm-slim

WORKDIR /app

RUN apt-get update \
    && apt-get install -y ffmpeg python3 python3-pip \
    && python3 -m pip install --no-cache-dir --break-system-packages yt-dlp \
    && rm -rf /var/lib/apt/lists/*

COPY package*.json ./

RUN npm ci --omit=dev 

COPY  --chown=node:node . . 

RUN mkdir -p /app/downloads && chown node:node /app/downloads

ENV NODE_ENV=production

USER node

CMD [ "node","src/worker.js" ]